# Generated by Django 5.1.7 on 2025-03-23 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0002_membership_club_alter_membership_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTerminationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_requests', to='users.membership')),
            ],
        ),
    ]
