# Generated by Django 5.1.1 on 2025-03-11 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_member', '0002_initial'),
        ('users', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipterminationrequest',
            name='club_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_requests', to='users.clubmember'),
        ),
        migrations.DeleteModel(
            name='ClubMember',
        ),
    ]
