# Generated by Django 5.1.7 on 2025-03-22 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'club')},
        ),
    ]
