# Generated by Django 5.1.7 on 2025-03-25 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_directmessage_receiver_alter_directmessage_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directchatroom',
            unique_together={('user1', 'user2')},
        ),
        migrations.RemoveField(
            model_name='directchatroom',
            name='club',
        ),
    ]
