# Generated by Django 5.1.1 on 2025-03-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_status_clubactivity_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='status',
        ),
    ]
