# Generated by Django 5.1.1 on 2025-03-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
