# Generated by Django 5.1.1 on 2025-03-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_event_reschedulerequest_delete_clubactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='event_date',
        ),
    ]
