# Generated by Django 5.1.1 on 2025-03-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_rename_datetime_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club'),
        ),
    ]
